version: '3.1'

services:
  php:
    container_name: gamingtwitter_php
    build: ./docker
    volumes:
      - .:/var/www
    links:
      - database
    environment:
      TZ: Asia/Tokyo

  nginx:
    image: nginx:latest
    container_name: gamingtwitter_nginx
    ports:
      - 82:80
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  database:
    image: mysql:5.7
    container_name: gamingtwitter_mysqld
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      # - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      # - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3334:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gamingtwitter
      MYSQL_USER: gamingtwitter_user
      MYSQL_PASSWORD: secret
      TZ: 'Asia/Tokyo'
